Use Cuda?  True
cuda: 0
Creating CNN model...
Using SSD loss...
Traceback (most recent call last):
  File "train.py", line 131, in <module>
    random_sample        = args.random_sample)
  File "/home/mmasramo/ProsRegNet/data/synth_dataset.py", line 37, in __init__
    self.train_data     = pd.read_csv(csv_file)
  File "/share/apps/python-3.6.9-tkinter/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/share/apps/python-3.6.9-tkinter/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/share/apps/python-3.6.9-tkinter/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/share/apps/python-3.6.9-tkinter/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/share/apps/python-3.6.9-tkinter/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'training_data/tps/histo_mri_dwi_train2.csv'